### ISSUE TITLE
Instacart

### ISSUE THREAD

**Issue by mappu** [holman/extended-exercise-windows#14]
In this comment thread https://news.ycombinator.com/item?id=11607539 it's mentioned that Instacart has a 7-year exercise window. But i don't have any further citations to back that up.

**Comment by holman** [comment]
Yeah, saw that too. Would be curious to hear more, although a little shy of pulling the trigger without confirmation.

Wonder if we could get someone like @sferik in here with confirmation maybe.

**Comment by shiftb** [comment]
I can confirm. It's 7 years.

**Comment by holman** [comment]
🎉
