### ISSUE TITLE
Remove Asana from the list. Now publicly traded.

### ISSUE THREAD

**Issue by mattbond-qz** [holman/extended-exercise-windows#69]

**Comment by holman** [comment]
I think... maybe we want to keep them in there? I'm not sure. The original purpose is kind of to promote the companies doing things well, and it might still be a good signal that the companies *did* do it well in the past.

Maybe we add a new section below for alumni? What do people think?

**Comment by mattbond-qz** [comment]
Yeh sounds good to me. They did a good thing, and the take from a16z is
really a ridiculous one when you consider the DPO outcome for Asana.
